//! Spawns the agent on a PTY (portable-pty) with only the environment the
//! `Spawn` request carries (P8), and owns the single PTY writer thread.
//!
//! Exactly three kinds of bytes may be written to the PTY, all through the
//! one writer queue (P6):
//! 1. the bytes of an enumerated control key (`control_key_bytes`);
//! 2. `OperatorTerminalInput`: what a human types in the attach view;
//! 3. terminal-query replies generated by alacritty (see `screen`).
//!
//! Must NOT: write anything else to the PTY (in particular agent message
//! text), or block a caller when the queue is full.

use std::collections::BTreeMap;
use std::io::{Read, Write};
use std::path::Path;
use std::sync::mpsc::{SyncSender, TrySendError, sync_channel};

use agend_core::protocol::holder::{ControlKey, SpawnData};
use portable_pty::{CommandBuilder, MasterPty, PtySize, native_pty_system};

/// Writes waiting for the PTY; one more may be in flight in the writer thread.
pub const WRITE_QUEUE: usize = 64;
pub const DEFAULT_TERM: &str = "xterm-256color";

/// Bytes written to the PTY for a control key.
pub fn control_key_bytes(key: ControlKey) -> Option<&'static [u8]> {
    Some(match key {
        ControlKey::Esc => b"\x1b",
        ControlKey::Enter => b"\r",
        ControlKey::Up => b"\x1b[A",
        ControlKey::Down => b"\x1b[B",
        ControlKey::Right => b"\x1b[C",
        ControlKey::Left => b"\x1b[D",
        ControlKey::Digit1 => b"1",
        ControlKey::Digit2 => b"2",
        ControlKey::Digit3 => b"3",
        ControlKey::Y => b"y",
        ControlKey::N => b"n",
        ControlKey::Unknown => return None,
    })
}

#[derive(Debug, PartialEq, Eq)]
pub enum QueueError {
    /// The queue is full: the agent is not reading its input.
    Busy,
    /// The writer thread stopped (the PTY is gone).
    Closed,
}

/// Starts the writer thread and returns its queue.
pub fn start_writer(mut out: Box<dyn Write + Send>) -> SyncSender<Vec<u8>> {
    let (tx, rx) = sync_channel::<Vec<u8>>(WRITE_QUEUE);
    std::thread::Builder::new()
        .name("pty-writer".into())
        .spawn(move || {
            for bytes in rx {
                if out.write_all(&bytes).and_then(|()| out.flush()).is_err() {
                    break;
                }
            }
        })
        .expect("spawn pty-writer thread");
    tx
}

/// Queues bytes for the PTY without waiting.
pub fn enqueue(queue: &SyncSender<Vec<u8>>, bytes: Vec<u8>) -> Result<(), QueueError> {
    queue.try_send(bytes).map_err(|e| match e {
        TrySendError::Full(_) => QueueError::Busy,
        TrySendError::Disconnected(_) => QueueError::Closed,
    })
}

pub struct SpawnedAgent {
    pub pid: u32,
    pub master: Box<dyn MasterPty + Send>,
    pub reader: Box<dyn Read + Send>,
    pub writer: Box<dyn Write + Send>,
}

/// The agent's environment: exactly `env`, plus `TERM` when it is missing.
pub fn agent_env(env: &BTreeMap<String, String>) -> BTreeMap<String, String> {
    let mut out = env.clone();
    out.entry("TERM".into())
        .or_insert_with(|| DEFAULT_TERM.into());
    out
}

/// Starts the agent in its own session on a new PTY (portable-pty calls
/// `setsid`, so the agent's process group id is its pid).
pub fn spawn(data: &SpawnData, rows: u16, columns: u16) -> Result<SpawnedAgent, String> {
    if !Path::new(&data.working_directory).is_dir() {
        return Err(format!(
            "working directory {} is not a directory",
            data.working_directory
        ));
    }
    let pair = native_pty_system()
        .openpty(PtySize {
            rows,
            cols: columns,
            pixel_width: 0,
            pixel_height: 0,
        })
        .map_err(|e| format!("openpty: {e}"))?;
    let mut cmd = CommandBuilder::new(&data.program);
    cmd.args(&data.args);
    cmd.env_clear();
    for (key, value) in agent_env(&data.env) {
        cmd.env(key, value);
    }
    cmd.cwd(&data.working_directory);
    let child = pair
        .slave
        .spawn_command(cmd)
        .map_err(|e| format!("spawn {}: {e}", data.program))?;
    let pid = child
        .process_id()
        .ok_or_else(|| "spawned agent has no pid".to_string())?;
    // The holder reaps the agent itself with waitpid (see `exit`).
    drop(child);
    // Close our copy of the slave so reading the master ends when the agent does.
    drop(pair.slave);
    let reader = pair
        .master
        .try_clone_reader()
        .map_err(|e| format!("pty reader: {e}"))?;
    let writer = pair
        .master
        .take_writer()
        .map_err(|e| format!("pty writer: {e}"))?;
    Ok(SpawnedAgent {
        pid,
        master: pair.master,
        reader,
        writer,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::mpsc::{Receiver, channel};

    #[test]
    fn control_keys_are_single_bytes() {
        assert_eq!(control_key_bytes(ControlKey::Esc), Some(&[0x1b][..]));
        assert_eq!(control_key_bytes(ControlKey::Digit1), Some(b"1".as_slice()));
        assert_eq!(control_key_bytes(ControlKey::Unknown), None);
    }

    #[test]
    fn env_is_exactly_the_spawn_env_plus_default_term() {
        let given = BTreeMap::from([("A".to_string(), "1".to_string())]);
        assert_eq!(
            agent_env(&given),
            BTreeMap::from([
                ("A".to_string(), "1".to_string()),
                ("TERM".to_string(), DEFAULT_TERM.to_string()),
            ])
        );
        let own_term = BTreeMap::from([("TERM".to_string(), "dumb".to_string())]);
        assert_eq!(agent_env(&own_term), own_term);
    }

    /// A PTY stand-in whose writes block until the test releases them.
    struct Stuck(Receiver<()>);

    impl Write for Stuck {
        fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
            let _ = self.0.recv();
            Ok(buf.len())
        }
        fn flush(&mut self) -> std::io::Result<()> {
            Ok(())
        }
    }

    #[test]
    fn a_full_queue_reports_busy_instead_of_blocking() {
        let (release, gate) = channel();
        let queue = start_writer(Box::new(Stuck(gate)));
        // One write may already be in flight; after that the queue holds 64.
        let mut accepted = 0;
        let outcome = loop {
            match enqueue(&queue, b"x".to_vec()) {
                Ok(()) => accepted += 1,
                Err(e) => break e,
            }
            assert!(accepted <= WRITE_QUEUE + 1, "queue never filled");
        };
        assert_eq!(outcome, QueueError::Busy);
        assert!(accepted >= WRITE_QUEUE, "accepted only {accepted}");
        drop(release); // unblocks the writer; its thread then ends
    }
}
