//! Option specs (exact spellings, see `opts`) for every git subcommand whose
//! verdict depends on its options. Taken from `git <cmd> -h` (git 2.39) plus
//! the `--no-*` negations the policies tolerate. An option missing here is
//! refused with "spell it in full"; add it here (and to the policy, if it
//! matters) rather than loosening the parser.
//!
//! Must NOT: list an option whose effect the command's policy ignores when it
//! matters (e.g. a `--no-dry-run` that would cancel a dry run).

/// A spec: groups of entries (shared groups avoid copy-paste).
pub type Spec = &'static [&'static [&'static str]];

/// The spec for `sub`, if the shim inspects its options.
pub fn of(sub: &str) -> Option<Spec> {
    Some(match sub {
        "push" => &[PUSH],
        "fetch" => &[FETCH_COMMON, FETCH],
        "pull" => &[FETCH_COMMON, PULL],
        "checkout" => &[SWITCH_COMMON, CHECKOUT],
        "switch" => &[SWITCH_COMMON, SWITCH],
        "branch" => &[BRANCH],
        "tag" => &[TAG],
        "reset" => &[RESET],
        "clean" => &[CLEAN],
        "restore" => &[RESTORE],
        "update-ref" => &[UPDATE_REF],
        "symbolic-ref" => &[SYMBOLIC_REF],
        "config" => &[CONFIG],
        "rebase" => &[REBASE],
        "read-tree" => &[READ_TREE],
        "rm" => &[RM],
        _ => return None,
    })
}

const PUSH: &[&str] = &[
    "-v|--verbose",
    "-q|--quiet",
    "--repo=",
    "--all",
    "--branches",
    "--mirror",
    "-d|--delete",
    "--tags",
    "-n|--dry-run",
    "--porcelain",
    "-f|--force",
    "--force-with-lease?",
    "--no-force-with-lease",
    "--force-if-includes",
    "--no-force-if-includes",
    "--recurse-submodules=",
    "--no-recurse-submodules",
    "--thin",
    "--no-thin",
    "--receive-pack=",
    "--exec=",
    "-u|--set-upstream",
    "--progress",
    "--no-progress",
    "--prune",
    "--no-verify",
    "--verify",
    "--follow-tags",
    "--no-follow-tags",
    "--signed?",
    "--no-signed",
    "--atomic",
    "--no-atomic",
    "-o|--push-option=",
    "-4|--ipv4",
    "-6|--ipv6",
];

/// Shared by `fetch` and `pull` (pull passes them to fetch).
const FETCH_COMMON: &[&str] = &[
    "-v|--verbose",
    "-q|--quiet",
    "--all",
    "--set-upstream",
    "-a|--append",
    "--upload-pack=",
    "-f|--force",
    "-t|--tags",
    "--no-tags",
    "-p|--prune",
    "--no-prune",
    "--dry-run",
    "-k|--keep",
    "--progress",
    "--no-progress",
    "--depth=",
    "--shallow-since=",
    "--shallow-exclude=",
    "--deepen=",
    "--unshallow",
    "--update-shallow",
    "--refmap=",
    "-o|--server-option=",
    "-4|--ipv4",
    "-6|--ipv6",
    "--negotiation-tip=",
    "--show-forced-updates",
    "--no-show-forced-updates",
    "--recurse-submodules?",
    "--no-recurse-submodules",
];

const FETCH: &[&str] = &[
    "--atomic",
    "-m|--multiple",
    "-n",
    "-j|--jobs=",
    "--prefetch",
    "-P|--prune-tags",
    "--write-fetch-head",
    "--no-write-fetch-head",
    "-u|--update-head-ok",
    "--refetch",
    "--filter=",
    "--negotiate-only",
    "--auto-maintenance",
    "--no-auto-maintenance",
    "--auto-gc",
    "--no-auto-gc",
    "--write-commit-graph",
    "--no-write-commit-graph",
    "--stdin",
    "--porcelain",
];

const PULL: &[&str] = &[
    "-r|--rebase?",
    "--no-rebase",
    "-n",
    "--stat",
    "--no-stat",
    "--log?",
    "--no-log",
    "--signoff?",
    "--no-signoff",
    "--squash",
    "--no-squash",
    "--commit",
    "--no-commit",
    "-e|--edit",
    "--no-edit",
    "--cleanup=",
    "--ff",
    "--no-ff",
    "--ff-only",
    "--verify",
    "--no-verify",
    "--verify-signatures",
    "--no-verify-signatures",
    "--autostash",
    "--no-autostash",
    "-s|--strategy=",
    "-X|--strategy-option=",
    "-S|--gpg-sign?",
    "--no-gpg-sign",
    "--allow-unrelated-histories",
    "-j|--jobs?",
    "--summary",
    "--no-summary",
    "--rerere-autoupdate",
    "--no-rerere-autoupdate",
    "--quiet-no-op",
];

/// Shared by `checkout` and `switch`.
const SWITCH_COMMON: &[&str] = &[
    "--guess",
    "--no-guess",
    "-q|--quiet",
    "--recurse-submodules?",
    "--no-recurse-submodules",
    "--progress",
    "--no-progress",
    "-m|--merge",
    "--conflict=",
    "-d|--detach",
    "-t|--track?",
    "--no-track",
    "-f|--force",
    "--orphan=",
    "--overwrite-ignore",
    "--no-overwrite-ignore",
    "--ignore-other-worktrees",
];

const CHECKOUT: &[&str] = &[
    "-b=",
    "-B=",
    "-l",
    "--overlay",
    "--no-overlay",
    "-2|--ours",
    "-3|--theirs",
    "-p|--patch",
    "--ignore-skip-worktree-bits",
    "--pathspec-from-file=",
    "--pathspec-file-nul",
    "-U|--unified=",
    "--inter-hunk-context=",
];

const SWITCH: &[&str] = &["-c|--create=", "-C|--force-create=", "--discard-changes"];

const BRANCH: &[&str] = &[
    "-v|--verbose",
    "-q|--quiet",
    "-t|--track?",
    "--no-track",
    "-u|--set-upstream-to=",
    "--unset-upstream",
    "--color?",
    "--no-color",
    "-r|--remotes",
    "--contains*",
    "--no-contains*",
    "--abbrev?",
    "--no-abbrev",
    "-a|--all",
    "-d|--delete",
    "-D",
    "-m|--move",
    "-M",
    "-c|--copy",
    "-C",
    "-l|--list",
    "--show-current",
    "--create-reflog",
    "--edit-description",
    "-f|--force",
    "--merged*",
    "--no-merged*",
    "--column?",
    "--no-column",
    "--sort=",
    "--points-at*",
    "-i|--ignore-case",
    "--recurse-submodules",
    "--format=",
    "--omit-empty",
];

const TAG: &[&str] = &[
    "-l|--list",
    "-n?",
    "-d|--delete",
    "-v|--verify",
    "-a|--annotate",
    "-m|--message=",
    "-F|--file=",
    "-e|--edit",
    "--no-edit",
    "-s|--sign",
    "--no-sign",
    "--cleanup=",
    "-u|--local-user=",
    "-f|--force",
    "--create-reflog",
    "--column?",
    "--no-column",
    "--contains*",
    "--no-contains*",
    "--merged*",
    "--no-merged*",
    "--sort=",
    "--points-at*",
    "--format=",
    "--color?",
    "-i|--ignore-case",
    "--omit-empty",
    "--trailer=",
];

const RESET: &[&str] = &[
    "-q|--quiet",
    "--no-refresh",
    "--refresh",
    "--mixed",
    "--soft",
    "--hard",
    "--merge",
    "--keep",
    "--recurse-submodules?",
    "--no-recurse-submodules",
    "-p|--patch",
    "-N|--intent-to-add",
    "--pathspec-from-file=",
    "--pathspec-file-nul",
    "-U|--unified=",
    "--inter-hunk-context=",
];

const CLEAN: &[&str] = &[
    "-q|--quiet",
    "-n|--dry-run",
    "-f|--force",
    "-i|--interactive",
    "-d",
    "-e|--exclude=",
    "-x",
    "-X",
];

const RESTORE: &[&str] = &[
    "-s|--source=",
    "-S|--staged",
    "-W|--worktree",
    "--ignore-unmerged",
    "--overlay",
    "--no-overlay",
    "-q|--quiet",
    "--recurse-submodules?",
    "--no-recurse-submodules",
    "--progress",
    "--no-progress",
    "-m|--merge",
    "--conflict=",
    "-2|--ours",
    "-3|--theirs",
    "-p|--patch",
    "--ignore-skip-worktree-bits",
    "--pathspec-from-file=",
    "--pathspec-file-nul",
    "-U|--unified=",
    "--inter-hunk-context=",
];

const UPDATE_REF: &[&str] = &[
    "-m=",
    "-d",
    "--no-deref",
    "-z",
    "--stdin",
    "--create-reflog",
];

const SYMBOLIC_REF: &[&str] = &[
    "-q|--quiet",
    "-d|--delete",
    "--short",
    "--recurse",
    "--no-recurse",
    "-m=",
];

const CONFIG: &[&str] = &[
    "--global",
    "--system",
    "--local",
    "--worktree",
    "-f|--file=",
    "--blob=",
    "--get",
    "--get-all",
    "--get-regexp",
    "--get-urlmatch",
    "--replace-all",
    "--add",
    "--unset",
    "--unset-all",
    "--rename-section",
    "--remove-section",
    "-l|--list",
    "--fixed-value",
    "-e|--edit",
    "--get-color",
    "--get-colorbool",
    "-t|--type=",
    "--bool",
    "--int",
    "--bool-or-int",
    "--bool-or-str",
    "--path",
    "--expiry-date",
    "-z|--null",
    "--name-only",
    "--includes",
    "--no-includes",
    "--show-origin",
    "--show-scope",
    "--default=",
    // `git config <subcommand>` (git 2.46+)
    "--all",
    "--regexp",
    "--value=",
    "--url=",
    "--comment=",
    "--show-names",
    "--no-show-names",
];

const REBASE: &[&str] = &[
    "--onto=",
    "--keep-base",
    "--no-keep-base",
    "--no-verify",
    "--verify",
    "-q|--quiet",
    "-v|--verbose",
    "-n|--no-stat",
    "--stat",
    "--signoff",
    "--committer-date-is-author-date",
    "--reset-author-date",
    "--ignore-date",
    "-C=",
    "--ignore-whitespace",
    "--whitespace=",
    "-f|--force-rebase",
    "--no-ff",
    "--continue",
    "--skip",
    "--abort",
    "--quit",
    "--edit-todo",
    "--show-current-patch",
    "--apply",
    "-m|--merge",
    "-i|--interactive",
    "--rerere-autoupdate",
    "--no-rerere-autoupdate",
    "--empty=",
    "--autosquash",
    "--no-autosquash",
    "--update-refs",
    "--no-update-refs",
    "-S|--gpg-sign?",
    "--no-gpg-sign",
    "--autostash",
    "--no-autostash",
    "-x|--exec=",
    "-r|--rebase-merges?",
    "--no-rebase-merges",
    "--fork-point",
    "--no-fork-point",
    "-s|--strategy=",
    "-X|--strategy-option=",
    "--root",
    "--reschedule-failed-exec",
    "--no-reschedule-failed-exec",
    "--reapply-cherry-picks",
    "--no-reapply-cherry-picks",
    "-k|--keep-empty",
    "--no-keep-empty",
];

/// `--force` decides the snapshot, so no `--no-*` negations (a
/// `--no-cached` or `--no-dry-run` would cancel what the policy saw).
const RM: &[&str] = &[
    "-n|--dry-run",
    "-q|--quiet",
    "--cached",
    "-f|--force",
    "-r",
    "--ignore-unmatch",
    "--sparse",
    "--pathspec-from-file=",
    "--pathspec-file-nul",
];

const READ_TREE: &[&str] = &[
    "--index-output=",
    "--empty",
    "-v|--verbose",
    "-m",
    "--trivial",
    "--aggressive",
    "--reset",
    "--prefix=",
    "-u",
    "--exclude-per-directory=",
    "-i",
    "-n|--dry-run",
    "--no-sparse-checkout",
    "--debug-unpack",
    "--recurse-submodules?",
    "--no-recurse-submodules",
    "-q|--quiet",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn specs_are_well_formed() {
        for sub in [
            "push",
            "fetch",
            "pull",
            "checkout",
            "switch",
            "branch",
            "tag",
            "reset",
            "clean",
            "restore",
            "update-ref",
            "symbolic-ref",
            "config",
            "rebase",
            "read-tree",
            "rm",
        ] {
            let mut seen = std::collections::HashSet::new();
            for e in of(sub).unwrap().iter().flat_map(|g| g.iter()) {
                assert!(e.starts_with('-') && !e.contains(' '), "{sub}: {e:?}");
                for part in e.trim_end_matches(['=', '?', '*']).split('|') {
                    assert!(seen.insert(part), "{sub}: {part} listed twice");
                }
            }
        }
    }
}
